### ISSUE TITLE
[Cadastro Produtos] Cadastro de produtos

### ISSUE THREAD

**Issue by caiiquesantos** [ES-UFABC/SMA-Handshake-Eng-Software-2022.1-#12]
Criar formuláio para cadasto de produtos
- [x] Criar validação para usuário == produtor
- [x] Criar combobox para carregar mercadorias
- [x] Criar campo para cadastrar data de disponibilidade
- [x] Validação da data cadastrada maior que o dia atual
- [x] Criar campo para inserir a quantidade disponivel
- [x] Validação de quantidade maior que zero
- [x] Criar campo para cadastrar o preço da mercadoria
- [x] Validação de preço maior que zero
- [x] Criar método para cadastrar mercadoria no backend

Endpoints
- [x] Criar endpoint para carregar mercadorias disponiveis (GET)
- [x] Criar endpoint para gravar a mercadoria (POST)
- [x] Criar regra para validar o body do cadastro de mercadoria

**Comment by Hespius** [comment]
DESCRIÇÃO:

Enquanto produto desejo que seja desenvolvida a tela de cadastrar produtos para que seja utilizada pelo agricultor.

OBJETIVO:

Quando finalizada a tela deve conter todos os campos informados no detalhes técnicos e está funcional, fazendo as validações necessárias em cada campo.

CENÁRIO:

Dado que ao fazer login
Quando for identificado como user = agricultor
Então deve ser exibida a tela de cadastrar produtos para ele

DETALHES TÉCNICOS:

Cadastro produto Agricultor:

nome (aceita apenas texto)

quantidade (aceita apenas número)

valor (aceita apenas número)
