### ISSUE TITLE
[Busca Produtos] Busca de produtos para o consumidor

### ISSUE THREAD

**Issue by caiiquesantos** [ES-UFABC/SMA-Handshake-Eng-Software-2022.1-#13]
Criar formulário
- [x] Criar validação para usuário == consumidor
- [x] Criar campo para filtrar o produto
- [x] Criar campo para filtrar a quantidade
- [x] Criar campo para filtrar a data de disponibilidade
- [x] Criar método para buscar mercadorias do backend
- [x] Criar modal para exibir o resultado da busca

Endpoints:
- [x] Criar endpoint para carregar mercadorias disponiveis (GET)
- [x] Criar endpoint para buscar as mercadorias de acordo com os filtros aplicados (GET)

**Comment by Hespius** [comment]
- [ ] Criar validação para usuário = consumidor
- [ ] Criar barra de pesquisa 
- [ ] Criar campo para filtrar a quantidade
- [ ] Criar campo para filtrar a data de disponibilidade
- [ ] Modal retornando os dados da busca

**Comment by Hespius** [comment]
**DESCRIÇÃO:**

> Enquanto produto desejo que seja desenvolvida a tela de busca para que seja utilizada por clientes.

**OBJETIVO:**

> Quando finalizada a tela deve conter todos os campos informados no detalhes técnicos e está funcional, fazendo as validações necessárias em cada campo.

**CENÁRIO:**

> Dado que ao fazer login
> Quando for identificado como user = cliente
> Então deve ser exibida a tela de busca de produtos para ele

**DETALHES TÉCNICOS:**

Busca básica do usuário:

- barra de pesquisa (aceita somente texto)
- Campo Quantidade (aceita apenas números)
- Campo Data (aceita somente números)
- Modal para retornar os dados retornados na busca com os seguintes dados

```
{
"nome": "string"
"quantidade": 0.00,
"valor": 0.00
"nomeProdutor": "string"
"emailProdutor": "string"
"cidadeProdutor": "string"
"linkProdutor": "string"
}
```
